# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarketApp
  pod 'Alamofire'
  pod 'SwiftLint'
  pod 'ExytePopupView'
  pod 'Kingfisher'
  pod 'FirebaseAppCheck'
  #    pod 'Firebase/Crashlytics'

end
