# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarketApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarketApp
  #pod 'Alamofire'
  pod 'SwiftLint'
  pod 'ExytePopupView'
  pod 'Kingfisher'
  pod 'Moya'
  pod 'Moya/Combine', '~> 15.0'
  pod 'GoogleSignIn', '~> 6.2.4'
  
  #Firebase
  pod 'Firebase'
  pod 'FirebaseAuth' , '~> 9.6.0'
  pod 'FirebaseFirestore'
  pod 'FirebaseAppCheck', '~> 9.6.0'
  pod 'FirebaseFirestoreSwift'
  pod 'FirebaseMessaging'
  pod 'FirebaseStorage'
  pod 'FirebaseCrashlytics'
  pod 'FirebaseDynamicLinks'
  pod 'FirebasePerformance'
  pod 'FirebaseDatabase'
  pod 'FirebaseRemoteConfig'
  
  
  target 'MarketAppTests' do
    inherit! :search_paths
    # Pods for testing
    
  end
  
  target 'MarketAppUITests' do
    # Pods for testing
    
  end
  
  
end
